# Numpy

In [ ]:
# Installed Library

pip install numpy

In [2]:
# Import Library

import numpy as np

## Create Simple Array

In [22]:
x = np.array([1,2,3,4,5])
print(x)
x

[1 2 3 4 5]


array([1, 2, 3, 4, 5])

## One Dimension Array

In [12]:
arr = np.array([1,2,3,4,5])
print(arr)
arr

[1 2 3 4 5]


array([1, 2, 3, 4, 5])

## 2D Array

In [19]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
arr

[[1 2 3]
 [4 5 6]]


array([[1, 2, 3],
       [4, 5, 6]])

## 3D Array

In [21]:
arr = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr)
arr

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

## How to Check Dimension of the Array?

In [32]:
# 1-D Array

arr1 = np.array([1,2,3,4,5])

# 2-D Array

arr2 = np.array([[1,2,3,],[4,5,6]])

# 3-D Array

arr3 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])

# N-D Array (This is Used for Create Multi Dimension Array)

arr0 = np.array([[[[[[[[[[[[1,2,3,4,5]]]]]]]]]]]])

In [31]:
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)
print(arr0.ndim)

1
2
3
12


## How to Create Multi Dimension Array?

In [39]:
# 1- Way

arr1 = np.array([[[[[[[[[[[[1,2,3,4,5]]]]]]]]]]]])
print(arr1.ndim)

# 2- way

arr2 = np.array([1,2,3,4,5], ndmin = 5) # Where ndmin = dimension of the array. 
print(arr2.ndim)

12
5


# Special Type of Array.

### Zeros Array

In [58]:
# 1-D Zeros Array

arrx = np.zeros(3)
arrx

array([0., 0., 0.])

In [50]:
# 2-D Zeros Array

arry = np.zeros((2,4))
arry

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [59]:
# 3-D Zeros Array

arrz = np.zeros((1,3,3))
arrz

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

### Ones Array

In [65]:
# 1-D Ones Array

arrx = np.ones(5)
arrx

array([1., 1., 1., 1., 1.])

In [68]:
# 2-D Ones Array

arry = np.ones((3,4))
arry

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [69]:
# 3-D Ones Array

arrz = np.ones((2,3,4))
arrz

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

### Empty Arrya

In [75]:
# 1-D Empty Array

arrx = np.empty(2)
arrx

array([1., 1.])

In [76]:
# 2-D Empty Array

arry = np.empty((3,4))
arry

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [78]:
# 3-D Empty Array

arrz = np.empty((2,3,4))
arrz

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

### Range Array

In [86]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Diagonal Array

In [90]:
arrx = np.eye(5)
arrx

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [100]:
arry = np.eye(3,5)
arry

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [103]:
arrz = np.eye(4,6,3)
arrz

array([[0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0.]])

### Line Space Array

In [117]:
arrx = np.linspace(0,20, num =5)
arrx

array([ 0.,  5., 10., 15., 20.])

In [114]:
arrx = np.linspace(10, 200, num = 10)
arrx

array([ 10.        ,  31.11111111,  52.22222222,  73.33333333,
        94.44444444, 115.55555556, 136.66666667, 157.77777778,
       178.88888889, 200.        ])

## Create Array With Random Numbers

In [123]:
# Using Rand Function:-

arr = np.random.rand(4)
arr

array([0.90858366, 0.17642976, 0.65131182, 0.23944134])

In [143]:
arr1 = np.random.rand(10)*10
arr1

array([0.22189738, 6.67995295, 2.21885015, 1.78739823, 5.52925494,
       5.7199317 , 1.42672157, 5.56123753, 4.37834658, 2.98768101])

In [149]:
arr2 = np.random.rand(2,4)
arr2

array([[0.40077224, 0.71801514, 0.70613043, 0.38182651],
       [0.82606092, 0.07459227, 0.5688507 , 0.14390461]])

In [152]:
# Using Randn() Function:- 

# Note:- Randn() Function, generate the random value near to zero(Values are positive or Negitive both).

arr1 = np.random.randn(4)
arr1

array([-1.00471742, -0.74375084,  0.15677913, -1.40350911])

In [156]:
arr1 = np.random.randn(4,2)
arr1

array([[-0.32420462, -0.7003491 ],
       [-0.31518589,  0.32082202],
       [ 0.43186921,  0.44808968],
       [ 1.63739105, -0.43558441]])

In [158]:
# Using Randint Function:-

# Note:- Randint() Function, Generate the value between given range.

#Syntax:- (Mini, Max, Num. of Values)

arr = np.random.randint(1,10,4)
arr

array([8, 8, 9, 1])

### Find the Size of the Array?

In [161]:
arr_size = np.array([1,2,3,4,5,6,78,0])
print(arr_size.size)
arr_size.size

8


8

### Check Data-Type

In [169]:
arr1 = np.array([1,2,3,4])
arr1.dtype

dtype('int32')

In [165]:
arr2 = np.array([1.0,2,3,4])
arr2.dtype

dtype('float64')

In [168]:
arr3 = np.array([1.0,2.9,3.9,4.5])
arr3.dtype


dtype('float64')

### Type Casting / Inter-Change DataType

In [170]:
# Without Type Casting

X = np.array([1,2,3,45,6])
X.dtype

dtype('int32')

In [189]:
# With Type Casting

X = np.array([1,2,3,45,6], dtype = np.int64)
print(X)

[ 1  2  3 45  6]


In [188]:
Y = np.array([2,4,8,9,6])
# datatype = Y.astype(complex)
# datatype = Y.astype(bool)
# datatype = Y.astype(str)

datatype = Y.astype(float)
datatype

array([2., 4., 8., 9., 6.])

### Arthmetic Operation in NumPy

#### 1-D Array

In [202]:
x = np.array([1,2,3])
y = np.array([4,5,6])

print("Sum ==>", np.add(x,y))

print("Subtract ==>",np.subtract(x,y))

print("Multiply ==>" ,np.multiply(x,y))

print("Divide ==>" , np.divide(x,y))

print("Module ==>", np.mod(x,y))

print("Power ==>", np.power(x,y))

print("Reciprocal ==> ", np.reciprocal(y))

Sum ==> [5 7 9]
Subtract ==> [-3 -3 -3]
Multiply ==> [ 4 10 18]
Divide ==> [0.25 0.4  0.5 ]
Module ==> [1 2 3]
Power ==> [  1  32 729]
Reciprocal ==>  [0 0 0]


#### For 2-D Array

In [204]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8,9],[3,2,1]])

print(np.add(arr1,arr2))

print(np.multiply(arr1,arr2))

[[ 8 10 12]
 [ 7  7  7]]
[[ 7 16 27]
 [12 10  6]]


### Arthmetic Function

In [4]:
arr = np.array([2,67,98,56,78,24,90,25,37])

print(np.max(arr))
print(" ")

print(np.min(arr))
print(" ")

print(np.sqrt(arr))
print(" ")

arr2 = np.array([1,2,3,4,5,6,7,8,9,0])

print(np.cumsum(arr2))

98
 
2
 
[1.41421356 8.18535277 9.89949494 7.48331477 8.83176087 4.89897949
 9.48683298 5.         6.08276253]
 
[ 1  3  6 10 15 21 28 36 45 45]


### Shape

In [215]:
var1 = np.array([[1,2,3],[4,5,6]])
print(var1.shape)

(2, 3)


In [218]:
var2 = np.array([[[[[[[1,24,5,67,8,4,0,34,2,3]]]]]]])
print(var2.ndim)
print(var2)
print(var2.shape)

7
[[[[[[[ 1 24  5 67  8  4  0 34  2  3]]]]]]]
(1, 1, 1, 1, 1, 1, 10)


### ReShape The Array

In [225]:
arr = np.array([1,2,3,45,67,8,9,5,0])
print(arr)
print("  ")
print(arr.reshape(3,3))

[ 1  2  3 45 67  8  9  5  0]
  
[[ 1  2  3]
 [45 67  8]
 [ 9  5  0]]


#### Convert into 1-D Dimension.

In [231]:
array = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array)

# 1 - Way  
print(array.reshape(-1)) 

# 2nd - Way
print(array.ravel())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


### Array Slicilg

In [237]:
# 1-D Array Slicing

arr = np.array([1,2,3,4,5,6,7,8,90,12,23,34,45,56,67,78,89,9])
print(arr[1:7])   

[2 3 4 5 6 7]


In [242]:
 # 2-D Array Slicing

arr = np.array([[1,2,3,4,5,6],[12,23,34,45,56,67]])
print(arr[0,1:3])
print(arr[1,2:6])

[2 3]
[34 45 56 67]


### Iteration Array

#### For 1-D Array

In [251]:
arr = np.array([1,2,3,4,5,6,7,56,67,78,89,9])
for i in arr:
    print(i)

1
2
3
4
5
6
7
56
67
78
89
9


#### For 2-D Array

In [245]:
arr = np.array([[1,2,3,4,5,6],[12,23,34,45,56,67]])

for i in arr:
    print(i)

[1 2 3 4 5 6]
[12 23 34 45 56 67]


In [246]:
arr = np.array([[1,2,3,4,5,6],[12,23,34,45,56,67]])

for i in arr:
    for j in i:
        print(j)

1
2
3
4
5
6
12
23
34
45
56
67


#### For 3-D Array

In [253]:
arr = np.array([[[1,2,3],[4,5,6],[7,8,9]]])

for i in arr:
    for j in i:
        for k in j:
            print(k)

1
2
3
4
5
6
7
8
9


#### Using Function:-

In [260]:
# 1-D Array
arr1 = np.array([1,2,3,4,5,6,7,56,67,78,89,9]) 
for i in np.nditer(arr1):
    print(i)

1
2
3
4
5
6
7
56
67
78
89
9


In [261]:
# 2-D Array
arr2 = np.array([[1,2,3,4,5,6],[12,23,34,45,56,67]])
for i in np.nditer(arr2):
    print(i)

1
2
3
4
5
6
12
23
34
45
56
67


In [262]:
# 3-D Array
arr3 = np.array([[[1,2,3],[4,5,6],[7,8,9]]]) 
for i in np.nditer(arr3):
    print(i)

1
2
3
4
5
6
7
8
9


### Join Array

In [264]:
# 1-D Array

arr1 = np.array([1,2,3,4])
arr2 = np.array([0,9,8,7])

joinarr = np.concatenate((arr1,arr2))
print(joinarr)

[1 2 3 4 0 9 8 7]


In [266]:
# 2-D Array

arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[11,22,33], [44,55,66]])
print(np.concatenate((arr1,arr2), axis = 1))
print(np.concatenate((arr1,arr2), axis = 0))

[[ 1  2  3 11 22 33]
 [ 4  5  6 44 55 66]]
[[ 1  2  3]
 [ 4  5  6]
 [11 22 33]
 [44 55 66]]


In [274]:
# Join Array Using for 
arr1 = np.array([1,2,3,4])
print(np.dstack(arr1))
print(np.hstack(arr1))
print(np.vstack(arr1))
print(np.stack(arr1))

[[[1 2 3 4]]]
[1 2 3 4]
[[1]
 [2]
 [3]
 [4]]
[1 2 3 4]


## Array Splir

In [282]:
# In 1-D Array

arr = np.array([1,2,3,4,5,6,7,8])
splt = np.array_split(arr, 5)
print(splt)

[array([1, 2]), array([3, 4]), array([5, 6]), array([7]), array([8])]


In [286]:
# In 2-D Array

arr = np.array([[11,22,33], [44,55,66]])
print(np.array_split(arr, 2))

[array([[11, 22, 33]]), array([[44, 55, 66]])]


## Searching in Array

#### Search value and return index.

In [302]:
arr1 = np.array([1,2,3,4,5,6,7,56,67,78,89,9]) 
x1 = np.searchsorted(arr1,5)
print(x1)

4


#### Sort Array

In [314]:
arr1 = np.array([1,2,3,4,5,6,7,56,67,78,89,9]) 
arr = np.array([[110,22,330], [44,55,66]])

print(np.sort(arr))
print(np.sort(arr1))

[[ 22 110 330]
 [ 44  55  66]]
[ 1  2  3  4  5  6  7  9 56 67 78 89]


#### Unique Value 

In [319]:
arr = np.array([1,2,3,2,4,5,3,4,2,45,5,6,8,7,9,7,6])
print(np.unique(arr))

[ 1  2  3  4  5  6  7  8  9 45]


#### Resize Array

In [321]:
arr = np.array([1,2,3,4,5,6,7,8,9,0])

print(np.resize(arr,(3,3)))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### Convert 2d array to 1d Array

In [322]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr.flatten())

[1 2 3 4 5 6]


#### Insert data into a Array

In [336]:
arr = np.array([1,2,3,4,5])
#Syntax = (arrat=yName, Index, Value)
print(np.insert(arr, 3, 33))    # Insert Single Value

print(np.insert(arr, [1,2,3], [22,33,44]))  # Insert Multiple Value

[ 1  2  3 33  4  5]
[ 1 22  2 33  3 44  4  5]


#### Insert One array into another Array

In [334]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([90,80,70])

print(np.insert(arr1,[2,3,1],arr2))

[ 1 70  2 90  3 80  4  5]


#### Data Insert into 2D Array

In [341]:
arr = np.array([[1,2,3],[4,5,6]])
print(np.insert(arr, 1,5, axis = 1))

[[1 5 2 3]
 [4 5 5 6]]


#### Delete Array Value

In [343]:
arr1 = np.array([1,2,3,4,5]) 

print(np.delete(arr1,3))

[1 2 3 5]


#### Transpose Array

In [345]:
arr1 = np.array([[1,2,3],[4,5,6]])

print(np.transpose(arr1))

[[1 4]
 [2 5]
 [3 6]]


In [346]:
arr = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
arr.T

array([[[1],
        [4],
        [7]],

       [[2],
        [5],
        [8]],

       [[3],
        [6],
        [9]]])

#### Swap the Matrix Axis

In [348]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(np.swapaxes(arr,0,1))

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


#### Inverse Matrix

In [351]:
arr = np.array([[1,2,],[4,5,]])
print(arr.dot(arr))

[[ 9 12]
 [24 33]]


#### Determinant of Matrix

In [353]:
arr = np.array([[1,2],[4,5]])
print(np.linalg.det(arr))

-2.9999999999999996


#### Full Up the Array

In [356]:
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [357]:
np.full((4,4), 6)

array([[6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6]])

#### Identity Array

In [367]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# ThankYou & Mark VaranVal